name: Index Posts

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  index-data:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.PAT }}

      # - name: Install Dependencies
      #   run: npm install

      - name: Index Posts
        run: node index-posts-data.js

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update posts index"
          commit_options: "--no-verify"
